# Generated by Django 3.0.2 on 2020-02-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hab', models.CharField(max_length=50, verbose_name='nombre habitacion')),
                ('cantidad_habitaciones', models.IntegerField(default=1, verbose_name='cantida de habitaciones')),
                ('precio', models.IntegerField(verbose_name='precio habitacion')),
                ('capacidad', models.IntegerField(verbose_name='capacidad de usuarios')),
                ('disponible', models.BooleanField(default=True, verbose_name='esta disponible')),
            ],
        ),
    ]
