# Generated by Django 3.0.2 on 2020-02-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='nombre_hab',
            new_name='nombre',
        ),
    ]
