# Generated by Django 3.0.2 on 2020-02-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_habitacion',
            name='Nombre_habitacion',
            field=models.CharField(default='Simple room', max_length=100, verbose_name='nombre habitacion'),
        ),
    ]
