# Generated by Django 3.0.2 on 2020-02-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_habitacion_nombre_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='cantidad_habitaciones',
            field=models.IntegerField(default=10, verbose_name='cantida de habitaciones'),
        ),
    ]
