# Generated by Django 3.0.2 on 2020-02-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20200211_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_egreso',
            field=models.IntegerField(max_length=10, verbose_name='fecha_egreso'),
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_ingreso',
            field=models.IntegerField(max_length=10, verbose_name='fecha_ingreso'),
        ),
    ]
