# Generated by Django 3.0.2 on 2020-02-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20200211_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva_habitacion',
            old_name='Numero_adultos',
            new_name='Numero_Personas',
        ),
        migrations.RemoveField(
            model_name='reserva_habitacion',
            name='Numero_menores',
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_egreso',
            field=models.CharField(max_length=20, verbose_name='fecha_egreso'),
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_ingreso',
            field=models.CharField(max_length=20, verbose_name='fecha_ingreso'),
        ),
    ]
