# Generated by Django 3.0.2 on 2020-02-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20200212_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Numero_Personas',
            field=models.IntegerField(verbose_name='Cantidad de Personas'),
        ),
    ]
