# Generated by Django 3.0.2 on 2020-02-29 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_auto_20200216_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_habitacion',
            name='Fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha en que se confirma la reserva'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='cantidad_habitaciones',
            field=models.IntegerField(default=10, verbose_name='cantidad de habitaciones'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='está disponible'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre habitación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.IntegerField(verbose_name='precio habitación'),
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_egreso',
            field=models.DateField(verbose_name='fecha egreso'),
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Fecha_ingreso',
            field=models.DateField(verbose_name='fecha ingreso'),
        ),
        migrations.AlterField(
            model_name='reserva_habitacion',
            name='Nombre_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Habitacion'),
        ),
    ]
