# Generated by Django 3.0.2 on 2020-02-26 02:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0008_auto_20200216_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='habitaciones/')),
                ('num_habitacion', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=0)),
                ('garaje', models.IntegerField(default=0)),
                ('camas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estrellas', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='hotel/')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=datetime.date.today)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pension', models.CharField(choices=[('completa', 'completa'), ('media', 'media'), ('desayuno', 'desayuno'), ('nada', 'nada')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Pension',
                'verbose_name_plural': 'Tipo Pensiones',
            },
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valoracion', models.IntegerField(default=0)),
                ('valoracion_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
                ('valoracion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.CreateModel(
            name='Tipo_alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('doble', 'doble'), ('individual', 'individual')], max_length=50)),
                ('precio', models.DecimalField(choices=[(200, 200), (100, 100)], decimal_places=2, max_digits=5)),
                ('habitacion_tipo_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Habitaciones')),
            ],
            options={
                'verbose_name': 'Tipo Alojamiento',
                'verbose_name_plural': 'Tipos Alojamientos',
            },
        ),
        migrations.CreateModel(
            name='Reservas_habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('ocupantes', models.IntegerField(default=0)),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Habitaciones')),
                ('reserva_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
            ],
            options={
                'verbose_name': 'Reserva habitacion',
                'verbose_name_plural': 'Reservas habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Precio_pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(choices=[(150.0, 150.0), (100.0, 100.0), (60.0, 60.0), (0.0, 0.0)], decimal_places=2, max_digits=5)),
                ('hotel_tipo_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Hotel')),
                ('precio_tipo_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Tipo_pension')),
            ],
            options={
                'verbose_name': 'Precio Pension',
                'verbose_name_plural': 'Precio Pensiones',
            },
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='habitacion_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Hotel'),
        ),
    ]
