# Generated by Django 3.0.2 on 2020-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_auto_20200301_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='capacidad',
            field=models.IntegerField(default=1),
        ),
    ]
