# Generated by Django 3.0.2 on 2020-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_habitaciones_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_habitacion',
            name='precio_total',
            field=models.IntegerField(default=0, verbose_name='precio_total'),
        ),
    ]
