# Generated by Django 3.0.2 on 2020-03-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_reservas_habitacion_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_habitacion',
            name='identificador',
            field=models.IntegerField(default=12341234, verbose_name='identificador'),
        ),
    ]
