# Generated by Django 3.0.2 on 2020-03-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reservas_habitacion_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_habitacion',
            name='metodo_de_pago',
            field=models.CharField(choices=[('MP', 'Mercado Pago'), ('Efec', 'Efectivo')], default='Pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='reservas_habitacion',
            name='status_payment',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendiente', 'Pendiente'), ('Fallo', 'Fallo'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100),
        ),
    ]
