# Generated by Django 3.0.2 on 2020-03-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_auto_20200324_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_habitacion',
            name='metodo_de_pago',
            field=models.CharField(choices=[('Mercado Pago', 'Mercado Pago'), ('Efectivo', 'Efectivo'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=100),
        ),
    ]
