# Generated by Django 3.0.2 on 2020-04-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_cantidadreservas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantidadreservas',
            options={'verbose_name': 'Cantidad de Reservas', 'verbose_name_plural': 'Cantidad de Reservas'},
        ),
        migrations.AlterField(
            model_name='reservas_habitacion',
            name='status_payment',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendiente', 'Pendiente'), ('Fallo', 'Fallo'), ('Cancelado', 'Cancelado'), ('Activa', 'Activa'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='precio',
            field=models.DecimalField(choices=[(200, 200), (100, 100), (300, 300), (400, 400), (500, 500), (600, 600), (700, 700), (800, 800), (900, 900), (1000, 1000)], decimal_places=2, max_digits=5),
        ),
    ]
