# Generated by Django 3.0.2 on 2020-02-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='email',
            new_name='email_newsletter',
        ),
    ]
