# Generated by Django 3.0.2 on 2020-02-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_user',
            new_name='RegistroUsuario',
        ),
        migrations.RenameField(
            model_name='registrousuario',
            old_name='password',
            new_name='password1',
        ),
    ]
