# Generated by Django 3.0.3 on 2020-02-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200221_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroUsuario',
        ),
    ]
