# Generated by Django 3.0.2 on 2020-02-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200219_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrousuario',
            old_name='password1',
            new_name='password',
        ),
    ]
